http:
  port: 5000
  readTimeout: 10s
  writeTimeout: 10s
  maxHeaderMegabytes: 2

cache:
  ttl: 60s

limiter:
  rps: 10
  burst: 20
  ttl: 10m

postgres:
  name: storage
  port: 5432
  host: localhost
  user: postgres